Yimura/GTAV-Classes

CTunables.hpp, atSingleton.hpp
This PR adds the CTunables class from @brunph.
=> feat(CTunables): Added new class

rage/fwEntity.hpp
Mission bits can be used to check if an entity is a mission entity.
=> Added mission bits to fwEntity.

base/CBaseModelInfo.hpp, base/datBase.hpp, base/fwExtensibleBase.hpp, base/fwExtension.hpp, base/fwExtensionContainer.hpp, base/fwRefAwareBase.hpp, base/fwRefAwareBaseImpl.hpp, base/pgBase.hpp, datanodes/player/CPlayerGameStateDataNode.hpp, rage/fwEntity.hpp, vehicle/CVehicleModelInfo.hpp
Some minor fixes and additions.
=> fix(CPlayerGameStateDataNode, fwEntity, & CBaseModelInfo): Updated classes.

vehicle/CVehicleModelInfo.hpp, weapon/CWeaponInfo.hpp
yeah. thats all. I did not much
=> updated enums eVehicleType,eDamageType 

weapon/CWeaponInfo.hpp
=> accidentally forgot to change offset in pr

.gitignore, network/CNetComplaintMgr.hpp, network/Network.hpp, network/snSession.hpp, rage/rlGamerInfo.hpp, rage/rlGamerInfoBase.hpp, rage/rlMetric.hpp, security/Obf32.hpp
Should I split the files further?
=> Add network classes

socialclub/FriendRegistry.hpp
Removes the FriendsList class and I added an inlined method that allows you to easily get a FriendInfo from the FriendRegistry.
=> refactor: Simplify FriendRegistry

base/CNavigation.hpp, base/phArchetype.hpp, base/phBoundComposite.hpp, ped/CPed.hpp, player/CPlayerInfo.hpp, rage/vector.hpp, vehicle/CVehicle.hpp
* Added get_position() helper to CNavigation
* Updated CPed class:
* m_fatigued_health_threshold
* m_injured_health_threshold
* m_dying_health_threshold
* m_hurt_health_threshold
* Updated CPlayerInfo class:
* m_wanted_level_difficulty
* m_wanted_level_multiplier
* Updated CVehicle class:
* m_dirt_level
* m_max_passengers
* m_num_of_passengers
* m_door_lock_status
=> feat(CPlayerInfo & CVehicle & CPed)

script/GtaThread.hpp, script/scrProgramTable.hpp
=> fix: GtaThread & scrProgramTable

network/CCommunications.cpp, network/CCommunications.hpp
I need this to prevent the game from crashing when the host token is modified
=> Add unknown voice related classes

rage/atArray.hpp
=> feat(rage): added atArray class

ped/CPed.hpp
- get_speed
- can_be_ragdolled
- get_ped_type
- has_seatbelt
- forced_aim
=> CPed functions

datanodes/ped/CPedTaskSpecificDataNode.hpp
=> feat(Data Nodes): Add CPedTaskSpecificDataNode.

network/ChatData.hpp
Thanks to @yubie-re for giving me the correctly sized members and finding the other class members as well.
=> feat(ChatData): Added other chat fields

datanodes/task/CClonedGeneralSweepInfo.hpp
=> CClonedGeneralSweepInfo

ped/CPedModelInfo.hpp
Thanks to @SkiddyToast 
refer to [#1156](https://github.com/YimMenu/YimMenu/pull/1156)
=> ped_type for CPedModelInfo

vehicle/CVehicle.hpp
- Added current gear
- Added next gear
- Added top gear
- Added engine rpm
=> feat(CVehicle): expand vehicle class

script/scrVector.hpp
Added == and != operators to the srcVector
=> srcVector operators

rage/scrValue.hpp, script/scrProgram.hpp, script/scrThread.hpp
Updated scrProgram and added scrValue for a future YimMenu commit
=> Added scrValue

rage/gameSkeleton.hpp
Credits to maybegreat for initial reversal in his AC bypass.
=> gameSkeleton classes

network/CNetGamePlayerDataMsg.hpp
Fixes https://github.com/YimMenu/YimMenu/issues/2918
Fixes https://github.com/YimMenu/YimMenu/issues/2595
=> Fix CNetGamePlayerDataMsg
